/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import ordenacao.GeradorDeGrafico;
import ordenacao.Ordenacao;
import static ordenacao.Ordenacao.*;

/**
 *
 * @author Gnomo
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }
    //ArrayList
    
    ArrayList<String> dadosTempo = new ArrayList<>();
    ArrayList<String> dadosTrocas = new ArrayList<>();
    ArrayList<String> dadosComparacoes = new ArrayList<>();
    
    //Gráfico
    GeradorDeGrafico grafico = new GeradorDeGrafico();
    //Getters
    
    public JCheckBox getCheckBubble() {
        return checkBubble;
    }

    public JCheckBox getCheckInsertion() {
        return checkInsertion;
    }

    public JCheckBox getCheckSelection() {
        return checkSelection;
    }

    public JCheckBox getCheckShake() {
        return checkShake;
    }

    public JCheckBox getCheckShell() {
        return checkShell;
    }

    public JTextField getFieldQtd() {
        return fieldQtd;
    }

    public JCheckBox getCheckComb() {
        return checkComb;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewGrafico = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        btnGraficoTempo = new javax.swing.JButton();
        btnGraficoComp = new javax.swing.JButton();
        btnGraficoTroca = new javax.swing.JButton();
        panelGrafico = new javax.swing.JPanel();
        panelGuias = new javax.swing.JTabbedPane();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnComparar = new javax.swing.JButton();
        fieldQtd = new javax.swing.JTextField();
        panelMetodos = new javax.swing.JPanel();
        checkSelection = new javax.swing.JCheckBox();
        checkInsertion = new javax.swing.JCheckBox();
        checkBubble = new javax.swing.JCheckBox();
        checkShake = new javax.swing.JCheckBox();
        checkComb = new javax.swing.JCheckBox();
        checkShell = new javax.swing.JCheckBox();
        panelSobreMetodos = new javax.swing.JPanel();
        guiasMetodos = new javax.swing.JTabbedPane();
        panelSelection = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        panelInsertion = new javax.swing.JPanel();
        panelBubble = new javax.swing.JPanel();
        panelShake = new javax.swing.JPanel();
        panelComb = new javax.swing.JPanel();
        panelShell = new javax.swing.JPanel();

        ViewGrafico.setTitle("GRÁFICOS");
        ViewGrafico.setMinimumSize(new java.awt.Dimension(640, 640));
        ViewGrafico.setName("ViewGrafico"); // NOI18N
        ViewGrafico.setResizable(false);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECIONE O TIPO DE GRÁFICO:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel7.setMaximumSize(new java.awt.Dimension(640, 50));
        jPanel7.setMinimumSize(new java.awt.Dimension(640, 50));
        jPanel7.setPreferredSize(new java.awt.Dimension(640, 50));

        btnGraficoTempo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGraficoTempo.setText("GRÁFICO DE TEMPO");
        btnGraficoTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoTempoActionPerformed(evt);
            }
        });

        btnGraficoComp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGraficoComp.setText("GRÁFICO DE COMPARAÇÕES");
        btnGraficoComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoCompActionPerformed(evt);
            }
        });

        btnGraficoTroca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGraficoTroca.setText("GRÁFICO DE TROCAS");
        btnGraficoTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoTrocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGraficoTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficoComp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficoTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGraficoTempo)
                    .addComponent(btnGraficoComp)
                    .addComponent(btnGraficoTroca))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelGrafico.setMaximumSize(new java.awt.Dimension(640, 500));
        panelGrafico.setMinimumSize(new java.awt.Dimension(640, 500));
        panelGrafico.setPreferredSize(new java.awt.Dimension(640, 500));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ViewGraficoLayout = new javax.swing.GroupLayout(ViewGrafico.getContentPane());
        ViewGrafico.getContentPane().setLayout(ViewGraficoLayout);
        ViewGraficoLayout.setHorizontalGroup(
            ViewGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ViewGraficoLayout.setVerticalGroup(
            ViewGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewGraficoLayout.createSequentialGroup()
                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setResizable(false);

        panelGuias.setMaximumSize(new java.awt.Dimension(640, 640));
        panelGuias.setMinimumSize(new java.awt.Dimension(640, 640));
        panelGuias.setPreferredSize(new java.awt.Dimension(640, 640));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/header.png"))); // NOI18N

        btnComparar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnComparar.setText("COMPARAR");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });

        fieldQtd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldQtd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantos números deseja gerar?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        fieldQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQtdActionPerformed(evt);
            }
        });

        panelMetodos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione os métodos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        checkSelection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkSelection.setText("Selection");

        checkInsertion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkInsertion.setText("Insertion");

        checkBubble.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkBubble.setText("Bubble");

        checkShake.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkShake.setText("Shake");

        checkComb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkComb.setText("Comb");

        checkShell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkShell.setText("Shell");

        javax.swing.GroupLayout panelMetodosLayout = new javax.swing.GroupLayout(panelMetodos);
        panelMetodos.setLayout(panelMetodosLayout);
        panelMetodosLayout.setHorizontalGroup(
            panelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkSelection)
                .addGap(18, 18, 18)
                .addComponent(checkInsertion)
                .addGap(18, 18, 18)
                .addComponent(checkBubble)
                .addGap(18, 18, 18)
                .addComponent(checkShake)
                .addGap(18, 18, 18)
                .addComponent(checkComb)
                .addGap(18, 18, 18)
                .addComponent(checkShell)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMetodosLayout.setVerticalGroup(
            panelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSelection)
                    .addComponent(checkInsertion)
                    .addComponent(checkBubble)
                    .addComponent(checkShake)
                    .addComponent(checkComb)
                    .addComponent(checkShell))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fieldQtd)
            .addComponent(btnComparar, javax.swing.GroupLayout.Alignment.CENTER)
            .addComponent(panelMetodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComparar)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        panelGuias.addTab("INÍCIO", panelPrincipal);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("A ordenação por seleção (do inglês, selection sort) é um algoritmo de ordenação \nbaseado em se passar sempre o menor valor do vetor para a primeira posição\n(ou o maior dependendo da ordem requerida), depois o de segundo menor valor \npara a segunda posição, e assim é feito sucessivamente com os n − 1 elementos \nrestantes, até os últimos dois elementos.");
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SOBRE:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setText("O(n²)");
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMPLEXIDADE:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("• Ele é um algoritmo simples de ser implementado em comparação aos demais.\n• Não necessita de um vetor auxiliar (in-place).\n• Por não usar um vetor auxiliar para realizar a ordenação, ele ocupa menos\nmemória.\n• Ele é uns dos mais velozes na ordenação de vetores de tamanhos pequenos.");
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VANTAGENS:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("• Ele é um dos mais lentos para vetores de tamanhos grandes.\n• Ele não é estável.\n• Ele faz sempre ( n² − n ) / 2 comparações, independente do vetor \nestá ordenado ou não.");
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESVANTAGENS:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        javax.swing.GroupLayout panelSelectionLayout = new javax.swing.GroupLayout(panelSelection);
        panelSelection.setLayout(panelSelectionLayout);
        panelSelectionLayout.setHorizontalGroup(
            panelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSelectionLayout.createSequentialGroup()
                        .addGroup(panelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSelectionLayout.setVerticalGroup(
            panelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        guiasMetodos.addTab("SELECTION", panelSelection);

        javax.swing.GroupLayout panelInsertionLayout = new javax.swing.GroupLayout(panelInsertion);
        panelInsertion.setLayout(panelInsertionLayout);
        panelInsertionLayout.setHorizontalGroup(
            panelInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInsertionLayout.setVerticalGroup(
            panelInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("INSERTION", panelInsertion);

        javax.swing.GroupLayout panelBubbleLayout = new javax.swing.GroupLayout(panelBubble);
        panelBubble.setLayout(panelBubbleLayout);
        panelBubbleLayout.setHorizontalGroup(
            panelBubbleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBubbleLayout.setVerticalGroup(
            panelBubbleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("BUBBLE", panelBubble);

        javax.swing.GroupLayout panelShakeLayout = new javax.swing.GroupLayout(panelShake);
        panelShake.setLayout(panelShakeLayout);
        panelShakeLayout.setHorizontalGroup(
            panelShakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelShakeLayout.setVerticalGroup(
            panelShakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("SHAKE", panelShake);

        javax.swing.GroupLayout panelCombLayout = new javax.swing.GroupLayout(panelComb);
        panelComb.setLayout(panelCombLayout);
        panelCombLayout.setHorizontalGroup(
            panelCombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCombLayout.setVerticalGroup(
            panelCombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("COMB", panelComb);

        javax.swing.GroupLayout panelShellLayout = new javax.swing.GroupLayout(panelShell);
        panelShell.setLayout(panelShellLayout);
        panelShellLayout.setHorizontalGroup(
            panelShellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelShellLayout.setVerticalGroup(
            panelShellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("SHELL", panelShell);

        javax.swing.GroupLayout panelSobreMetodosLayout = new javax.swing.GroupLayout(panelSobreMetodos);
        panelSobreMetodos.setLayout(panelSobreMetodosLayout);
        panelSobreMetodosLayout.setHorizontalGroup(
            panelSobreMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guiasMetodos, javax.swing.GroupLayout.Alignment.CENTER)
        );
        panelSobreMetodosLayout.setVerticalGroup(
            panelSobreMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guiasMetodos)
        );

        panelGuias.addTab("SOBRE OS MÉTODOS", panelSobreMetodos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGuias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGuias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQtdActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        // TODO add your handling code here:
        Ordenacao ordenacao = new Ordenacao();
        panelGrafico.removeAll();
        
        ordenacao.compararMetodos(this);
        dadosTempo = tempos;
        dadosTrocas = trocas;
        dadosComparacoes = comparacoes;
        
        panelGrafico.add(grafico.gerarGrafico(dadosTempo, 0));
        panelGrafico.revalidate();
        panelGrafico.repaint();
        ViewGrafico.setLocationRelativeTo(null);
        ViewGrafico.setVisible(true);
    }//GEN-LAST:event_btnCompararActionPerformed

    private void btnGraficoTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoTempoActionPerformed
        // TODO add your handling code here:
        panelGrafico.removeAll();
        panelGrafico.add(grafico.gerarGrafico(dadosTempo, 0));
        panelGrafico.revalidate();
        panelGrafico.repaint();
    }//GEN-LAST:event_btnGraficoTempoActionPerformed

    private void btnGraficoCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoCompActionPerformed
        // TODO add your handling code here:
        panelGrafico.removeAll();
        panelGrafico.add(grafico.gerarGrafico(dadosComparacoes, 1));
        panelGrafico.revalidate();
        panelGrafico.repaint();
    }//GEN-LAST:event_btnGraficoCompActionPerformed

    private void btnGraficoTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoTrocaActionPerformed
        // TODO add your handling code here:
        panelGrafico.removeAll();
        panelGrafico.add(grafico.gerarGrafico(dadosTrocas, 2));
        panelGrafico.revalidate();
        panelGrafico.repaint();
    }//GEN-LAST:event_btnGraficoTrocaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ViewGrafico;
    public javax.swing.JButton btnComparar;
    private javax.swing.JButton btnGraficoComp;
    private javax.swing.JButton btnGraficoTempo;
    private javax.swing.JButton btnGraficoTroca;
    private javax.swing.JCheckBox checkBubble;
    private javax.swing.JCheckBox checkComb;
    private javax.swing.JCheckBox checkInsertion;
    private javax.swing.JCheckBox checkSelection;
    private javax.swing.JCheckBox checkShake;
    private javax.swing.JCheckBox checkShell;
    private javax.swing.JTextField fieldQtd;
    private javax.swing.JTabbedPane guiasMetodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panelBubble;
    private javax.swing.JPanel panelComb;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JTabbedPane panelGuias;
    private javax.swing.JPanel panelInsertion;
    private javax.swing.JPanel panelMetodos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSelection;
    private javax.swing.JPanel panelShake;
    private javax.swing.JPanel panelShell;
    private javax.swing.JPanel panelSobreMetodos;
    // End of variables declaration//GEN-END:variables
}
