/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import ordenacao.GeradorDeGrafico;
import ordenacao.Ordenacao;
import static ordenacao.Ordenacao.*;

/**
 *
 * @author Gnomo
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }
    //ArrayList
    
    ArrayList<String> dadosTempo = new ArrayList<>();
    ArrayList<String> dadosTrocas = new ArrayList<>();
    ArrayList<String> dadosComparacoes = new ArrayList<>();
    
    //Gráfico
    GeradorDeGrafico grafico = new GeradorDeGrafico();
    //Getters
    
    public JCheckBox getCheckBubble() {
        return checkBubble;
    }

    public JCheckBox getCheckInsertion() {
        return checkInsertion;
    }

    public JCheckBox getCheckSelection() {
        return checkSelection;
    }

    public JCheckBox getCheckShake() {
        return checkShake;
    }

    public JCheckBox getCheckShell() {
        return checkShell;
    }

    public JTextField getFieldQtd() {
        return fieldQtd;
    }

    public JCheckBox getCheckComb() {
        return checkComb;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewGrafico = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        btnGraficoTempo = new javax.swing.JButton();
        btnGraficoComp = new javax.swing.JButton();
        btnGraficoTroca = new javax.swing.JButton();
        panelGrafico = new javax.swing.JPanel();
        panelGuias = new javax.swing.JTabbedPane();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnComparar = new javax.swing.JButton();
        fieldQtd = new javax.swing.JTextField();
        panelMetodos = new javax.swing.JPanel();
        checkSelection = new javax.swing.JCheckBox();
        checkInsertion = new javax.swing.JCheckBox();
        checkBubble = new javax.swing.JCheckBox();
        checkShake = new javax.swing.JCheckBox();
        checkComb = new javax.swing.JCheckBox();
        checkShell = new javax.swing.JCheckBox();
        panelSobreMetodos = new javax.swing.JPanel();
        guiasMetodos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        ViewGrafico.setTitle("GRÁFICOS");
        ViewGrafico.setMinimumSize(new java.awt.Dimension(640, 640));
        ViewGrafico.setName("ViewGrafico"); // NOI18N
        ViewGrafico.setResizable(false);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECIONE O TIPO DE GRÁFICO:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel7.setMaximumSize(new java.awt.Dimension(640, 50));
        jPanel7.setMinimumSize(new java.awt.Dimension(640, 50));
        jPanel7.setPreferredSize(new java.awt.Dimension(640, 50));

        btnGraficoTempo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGraficoTempo.setText("GRÁFICO DE TEMPO");
        btnGraficoTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoTempoActionPerformed(evt);
            }
        });

        btnGraficoComp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGraficoComp.setText("GRÁFICO DE COMPARAÇÕES");
        btnGraficoComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoCompActionPerformed(evt);
            }
        });

        btnGraficoTroca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGraficoTroca.setText("GRÁFICO DE TROCAS");
        btnGraficoTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoTrocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGraficoTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficoComp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficoTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGraficoTempo)
                    .addComponent(btnGraficoComp)
                    .addComponent(btnGraficoTroca))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelGrafico.setMaximumSize(new java.awt.Dimension(640, 500));
        panelGrafico.setMinimumSize(new java.awt.Dimension(640, 500));
        panelGrafico.setPreferredSize(new java.awt.Dimension(640, 500));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ViewGraficoLayout = new javax.swing.GroupLayout(ViewGrafico.getContentPane());
        ViewGrafico.getContentPane().setLayout(ViewGraficoLayout);
        ViewGraficoLayout.setHorizontalGroup(
            ViewGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ViewGraficoLayout.setVerticalGroup(
            ViewGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewGraficoLayout.createSequentialGroup()
                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setResizable(false);

        panelGuias.setMaximumSize(new java.awt.Dimension(640, 640));
        panelGuias.setMinimumSize(new java.awt.Dimension(640, 640));
        panelGuias.setPreferredSize(new java.awt.Dimension(640, 640));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/header.png"))); // NOI18N

        btnComparar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnComparar.setText("COMPARAR");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });

        fieldQtd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldQtd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantos números deseja gerar?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        fieldQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQtdActionPerformed(evt);
            }
        });

        panelMetodos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione os métodos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        checkSelection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkSelection.setText("Selection");

        checkInsertion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkInsertion.setText("Insertion");

        checkBubble.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkBubble.setText("Bubble");

        checkShake.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkShake.setText("Shake");

        checkComb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkComb.setText("Comb");

        checkShell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkShell.setText("Shell");

        javax.swing.GroupLayout panelMetodosLayout = new javax.swing.GroupLayout(panelMetodos);
        panelMetodos.setLayout(panelMetodosLayout);
        panelMetodosLayout.setHorizontalGroup(
            panelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkSelection)
                .addGap(18, 18, 18)
                .addComponent(checkInsertion)
                .addGap(18, 18, 18)
                .addComponent(checkBubble)
                .addGap(18, 18, 18)
                .addComponent(checkShake)
                .addGap(18, 18, 18)
                .addComponent(checkComb)
                .addGap(18, 18, 18)
                .addComponent(checkShell)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMetodosLayout.setVerticalGroup(
            panelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSelection)
                    .addComponent(checkInsertion)
                    .addComponent(checkBubble)
                    .addComponent(checkShake)
                    .addComponent(checkComb)
                    .addComponent(checkShell))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fieldQtd)
            .addComponent(btnComparar, javax.swing.GroupLayout.Alignment.CENTER)
            .addComponent(panelMetodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComparar)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        panelGuias.addTab("INÍCIO", panelPrincipal);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("TEXTO SOBRE O SELECTION\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
        );

        guiasMetodos.addTab("SELECTION", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("INSERTION", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("BUBBLE", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("SHAKE", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("COMB", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        guiasMetodos.addTab("SHELL", jPanel6);

        javax.swing.GroupLayout panelSobreMetodosLayout = new javax.swing.GroupLayout(panelSobreMetodos);
        panelSobreMetodos.setLayout(panelSobreMetodosLayout);
        panelSobreMetodosLayout.setHorizontalGroup(
            panelSobreMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guiasMetodos, javax.swing.GroupLayout.Alignment.CENTER)
        );
        panelSobreMetodosLayout.setVerticalGroup(
            panelSobreMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSobreMetodosLayout.createSequentialGroup()
                .addComponent(guiasMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        panelGuias.addTab("SOBRE OS MÉTODOS", panelSobreMetodos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGuias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGuias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQtdActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        // TODO add your handling code here:
        Ordenacao ordenacao = new Ordenacao();
        panelGrafico.removeAll();
        
        ordenacao.compararMetodos(this);
        dadosTempo = tempos;
        dadosTrocas = trocas;
        dadosComparacoes = comparacoes;
        
        panelGrafico.add(grafico.gerarGrafico(dadosTempo, 0));
        panelGrafico.revalidate();
        panelGrafico.repaint();
        ViewGrafico.setLocationRelativeTo(null);
        ViewGrafico.setVisible(true);
    }//GEN-LAST:event_btnCompararActionPerformed

    private void btnGraficoTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoTempoActionPerformed
        // TODO add your handling code here:
        panelGrafico.removeAll();
        panelGrafico.add(grafico.gerarGrafico(dadosTempo, 0));
        panelGrafico.revalidate();
        panelGrafico.repaint();
    }//GEN-LAST:event_btnGraficoTempoActionPerformed

    private void btnGraficoCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoCompActionPerformed
        // TODO add your handling code here:
        panelGrafico.removeAll();
        panelGrafico.add(grafico.gerarGrafico(dadosComparacoes, 1));
        panelGrafico.revalidate();
        panelGrafico.repaint();
    }//GEN-LAST:event_btnGraficoCompActionPerformed

    private void btnGraficoTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoTrocaActionPerformed
        // TODO add your handling code here:
        panelGrafico.removeAll();
        panelGrafico.add(grafico.gerarGrafico(dadosTrocas, 2));
        panelGrafico.revalidate();
        panelGrafico.repaint();
    }//GEN-LAST:event_btnGraficoTrocaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ViewGrafico;
    public javax.swing.JButton btnComparar;
    private javax.swing.JButton btnGraficoComp;
    private javax.swing.JButton btnGraficoTempo;
    private javax.swing.JButton btnGraficoTroca;
    private javax.swing.JCheckBox checkBubble;
    private javax.swing.JCheckBox checkComb;
    private javax.swing.JCheckBox checkInsertion;
    private javax.swing.JCheckBox checkSelection;
    private javax.swing.JCheckBox checkShake;
    private javax.swing.JCheckBox checkShell;
    private javax.swing.JTextField fieldQtd;
    private javax.swing.JTabbedPane guiasMetodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JTabbedPane panelGuias;
    private javax.swing.JPanel panelMetodos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSobreMetodos;
    // End of variables declaration//GEN-END:variables
}
